name: 2023-07-24-coffea-casa
channels:
  - conda-forge
dependencies:
  - dask
  - dask-awkward
  - dask-labextension
  - distributed
  - jupyterlab
  - jupyterlab-deck
  - matplotlib
  - numba
  - numpy
  - uproot
  - coffea
